-- unidade 1
CREATE TABLE CUSTOMER (
    ID NUMBER (4),
    NAME VARCHAR2 (50),
    ADDRESS VARCHAR2 (70) NOT NULL,
    CITY_CODE NUMBER (5),
    STATE_CODE CHAR (2),
    ZIP_CODE VARCHAR2 (8),
    AREA_CODE NUMBER (3),
    PHONE_NUMBER NUMBER(7),
    GENDER CHAR(1),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CUSTOMER_PK PRIMARY KEY (ID)
);

CREATE TABLE PURCHASE (
    CUSTOMER_ID NUMBER,
    PURCHASE_DATE DATE,
    PURCHASE_VALUE NUMBER (12, 2),
    CONSTRAINT PURCHASE_PK PRIMARY KEY (PURCHASE_DATE),
    CONSTRAINT PURCHASE_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

CREATE TABLE STATE (
    STATE_CODE CHAR(2) PRIMARY KEY,
    STATE_NAME VARCHAR2 (35),
    CONSTRAINT STATE_NAME_UN UNIQUE (STATE_NAME)
);

ALTER TABLE CUSTOMER ADD (CONSTRAINT CUSTOMER_STATE_CODE_FK FOREIGN KEY (STATE_CODE) REFERENCES STATE(STATE_CODE));

ALTER TABLE CUSTOMER ADD( IE_FISICA_JURIDICA CHAR(1));

ALTER TABLE CUSTOMER MODIFY (NAME NOT NULL);

ALTER TABLE CUSTOMER MODIFY (ADDRESS NUMBER(3));

ALTER TABLE CUSTOMER MODIFY (ZIP_CODE VARCHAR2(12));

ALTER TABLE CUSTOMER ADD(CONSTRAINT CUSTOMER_IE_FISICA_JURIDICA_CK CHECK(IE_FISICA_JURIDICA IN('F', 'J')));

ALTER TABLE CUSTOMER DISABLE CONSTRAINT CUSTOMER_IE_FISICA_JURIDICA_CK;

ALTER TABLE CUSTOMER DROP CONSTRAINT CUSTOMER_IE_FISICA_JURIDICA_CK;

-- DROP TABLE CUSTOMER; exemplo, precisaria de CASCADE

-- unidade 2
CREATE TABLE COUNTRY (
    COUNTRY_CODE NUMBER (2) PRIMARY KEY,
    COUNTRY_NAME CHAR (45),
    COUNTRY_NATIONALITY CHAR(35),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT COUNTRY_NAME_UN UNIQUE(COUNTRY_NAME)
);

ALTER USER UNIDADES_UNICSUL QUOTA UNLIMITED ON USERS;

INSERT INTO COUNTRY (
    COUNTRY_CODE,
    COUNTRY_NAME
) VALUES (
    1,
    'Brasil'
);

INSERT INTO COUNTRY (
    COUNTRY_CODE,
    COUNTRY_NAME,
    COUNTRY_NATIONALITY
)VALUES (
    2,
    'ARGENTINA',
    NULL
);

INSERT INTO COUNTRY VALUES (
    4,
    'CHILE',
    'CHILENA'
);

INSERT INTO COUNTRY (
    COUNTRY_NAME,
    COUNTRY_NATIONALITY,
    COUNTRY_CODE
)VALUES (
    'EUA',
    'AMERICANA',
    3
);

UPDATE COUNTRY
SET
    COUNTRY_NAME='PORTUGAL',
    COUNTRY_NATIONALITY='PORTUG'
WHERE
    COUNTRY_CODE = 3;

UPDATE COUNTRY
SET
    COUNTRY_NATIONALITY='PORTUGUESA'
WHERE
    COUNTRY_CODE = 3;

DELETE FROM COUNTRY
WHERE
    COUNTRY_CODE= 3;

ALTER TABLE COUNTRY RENAME TO COUNTRY_TABLE;

ALTER TABLE COUNTRY_TABLE RENAME TO COUNTRY;